viteloge_frontend_ad:
    resource: "@VitelogeFrontendBundle/Controller/AdController.php"
    type: annotation

viteloge_frontend_default:
    resource: "@VitelogeFrontendBundle/Controller/DefaultController.php"
    type: annotation

viteloge_frontend_query_stats:
    resource: "@VitelogeFrontendBundle/Controller/QueryStatsController.php"
    type: annotation

viteloge_frontend_glossary:
    resource: "@VitelogeFrontendBundle/Controller/GlossaryController.php"
    type: annotation

viteloge_frontend_user:
    resource: "@VitelogeFrontendBundle/Controller/UserController.php"
    type: annotation

viteloge_frontend_websearch:
    resource: "@VitelogeFrontendBundle/Controller/WebSearchController.php"
    type: annotation

viteloge_frontend_usersearch:
    resource: "@VitelogeFrontendBundle/Controller/UserSearchController.php"
    type: annotation

viteloge_frontend_service:
    resource: "@VitelogeFrontendBundle/Controller/ServiceController.php"
    type: annotation

viteloge_frontend_suggest:
    resource: "@VitelogeFrontendBundle/Controller/SuggestController.php"
    type: annotation

viteloge_frontend_message:
    resource: "@VitelogeFrontendBundle/Controller/MessageController.php"
    type: annotation

viteloge_frontend_contact:
    resource: "@VitelogeFrontendBundle/Controller/ContactController.php"
    type: annotation

viteloge_frontend_recommand:
    resource: "@VitelogeFrontendBundle/Controller/RecommandController.php"
    type: annotation

viteloge_frontend_api:
    resource: "@VitelogeFrontendBundle/Controller/ApiController.php"
    type: annotation

viteloge_frontend_sitemap:
    resource: "@VitelogeFrontendBundle/Controller/SitemapController.php"
    type: annotation

viteloge_frontend_static_about:
    path: /about
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'VitelogeFrontendBundle:Static:about.html.twig'
        private: true
        maxAge: 86400
        sharedAge: 86400
    requirements:
        _method: GET
    options:
        vl_sitemap:
            priority: 0.7
            changefreq: "weekly"
            title: viteloge.frontend.static.about.title
            description: viteloge.frontend.static.about.description

viteloge_frontend_static_why:
    path: /why
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'VitelogeFrontendBundle:Static:why.html.twig'
        private: true
        maxAge: 86400
        sharedAge: 86400
    requirements:
        _method: GET
    options:
        vl_sitemap:
            priority: 0.7
            changefreq: "weekly"
            title: viteloge.frontend.static.why.title
            description: viteloge.frontend.static.why.description

viteloge_frontend_static_ad:
    path: /ad
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'VitelogeFrontendBundle:Static:ad.html.twig'
        private: true
        maxAge: 86400
        sharedAge: 86400
    requirements:
        _method: GET
    options:
        vl_sitemap:
            priority: 0.7
            changefreq: "weekly"
            title: viteloge.frontend.static.ad.title
            description: viteloge.frontend.static.ad.description

viteloge_frontend_static_contactus:
    path: /contact-us
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'VitelogeFrontendBundle:Static:contactus.html.twig'
        private: true
        maxAge: 86400
        sharedAge: 86400
    requirements:
        _method: GET
    options:
        vl_sitemap:
            priority: 0.7
            changefreq: "weekly"
            title: viteloge.frontend.static.contactus.title
            description: viteloge.frontend.static.contactus.description

viteloge_frontend_static_recommand:
    path: /recommand
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'VitelogeFrontendBundle:Static:recommand.html.twig'
        private: true
        maxAge: 86400
        sharedAge: 86400
    requirements:
        _method: GET
    options:
        vl_sitemap:
            priority: 0.7
            changefreq: "weekly"
            title: viteloge.frontend.static.recommand.title
            description: viteloge.frontend.static.recommand.description

viteloge_frontend_static_subscribe:
    path: /subscribe
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'VitelogeFrontendBundle:Static:subscribe.html.twig'
        private: true
        maxAge: 86400
        sharedAge: 86400
    requirements:
        _method: GET
    options:
        vl_sitemap:
            priority: 0.7
            changefreq: "weekly"
            title: viteloge.frontend.static.subscribe.title
            description: viteloge.frontend.static.subscribe.description

viteloge_frontend_static_register:
    path: /register
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'VitelogeFrontendBundle:Static:register.html.twig'
        private: true
        maxAge: 86400
        sharedAge: 86400
    requirements:
        _method: GET
    options:
        vl_sitemap:
            priority: 0.7
            changefreq: "weekly"
            title: viteloge.frontend.static.register.title
            description: viteloge.frontend.static.register.description

viteloge_frontend_static_apiform:
    path: /apiform
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'VitelogeFrontendBundle:Static:apiform.html.twig'
        private: true
        maxAge: 86400
        sharedAge: 86400
    requirements:
        _method: GET
    options:
        vl_sitemap:
            priority: 0.7
            changefreq: "weekly"
            title: viteloge.frontend.static.apiform.title
            description: viteloge.frontend.static.apiform.description

viteloge_frontend_static_gtc:
    path: /gtc
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'VitelogeFrontendBundle:Static:gtc.html.twig'
        private: true
        maxAge: 86400
        sharedAge: 86400
    requirements:
        _method: GET
    options:
        vl_sitemap:
            priority: 0.7
            changefreq: "weekly"
            title: viteloge.frontend.static.gtc.title
            description: viteloge.frontend.static.gtc.description

viteloge_frontend_static_privacy:
    path: /privacy
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'VitelogeFrontendBundle:Static:privacy.html.twig'
        private: true
        maxAge: 86400
        sharedAge: 86400
    requirements:
        _method: GET
    options:
        vl_sitemap:
            priority: 0.7
            changefreq: "weekly"
            title: viteloge.frontend.static.privacy.title
            description: viteloge.frontend.static.privacy.description
