parameters:
    viteloge_frontend.form.type.ad.class: Viteloge\FrontendBundle\Form\Type\AdType
    viteloge_frontend.form.type.usersearch.class: Viteloge\FrontendBundle\Form\Type\UserSearchType
    viteloge_frontend.form.type.websearch.class: Viteloge\FrontendBundle\Form\Type\WebSearchType
    viteloge_frontend.twig.extension.class: Viteloge\FrontendBundle\Twig\VitelogeFrontendExtension

services:
    viteloge_frontend.form.type.ad:
        class: %viteloge_frontend.form.type.ad.class%
        tags:
            - { name: form.type, alias: viteloge_frontend_ad }
    viteloge_frontend.form.type.usersearch:
        class: %viteloge_frontend.form.type.usersearch.class%
        tags:
            - { name: form.type, alias: viteloge_frontend_usersearch }
    viteloge_frontend.form.type.websearch:
        class: %viteloge_frontend.form.type.websearch.class%
        tags:
            - { name: form.type, alias: viteloge_frontend_websearch }
    viteloge_frontend.twig.extension:
        class: %viteloge_frontend.twig.extension.class%
        arguments:
            - @service_container
        tags:
            - { name: twig.extension, priority: 255 }
