hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /user/connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /user/login

facebook_login:
    path: /user/login/check-facebook

google_login:
    path: /user/login/check-google

twitter_login:
    path: /user/login/check-twitter

github_login:
    path: /user/login/check-github
