imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: swiftmailer.yml }
    - { resource: doctrine_migrations.yml }
    - { resource: sonata_seo.yml }
    - { resource: fos_js_routing.yml }
    - { resource: fos_elastica.yml }
    - { resource: fos_user.yml }
    - { resource: white_october_breadcrumbs.yml }
    - { resource: white_october_pagerfanta.yml }
    - { resource: stof_doctrine_extension.yml }
    - { resource: genemu_form.yml }
    - { resource: hwi_oauth.yml }
    - { resource: ewz_recaptcha.yml }
    - { resource: jms_i18n_routing.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
        name: VITELOGE_SESSID
        cookie_domain: %domain%
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources: ['AcreatCoreBundle:Form:fields.html.twig', 'VitelogeCoreBundle:Form:fields.html.twig']
    exception_controller:  viteloge_twig.controller.exception:showAction
    globals:
        domain: %domain%
        media_domain: %media_domain%
        ga_tracking: %ga_tracking%
        adsense_publisher_id: %adsense_publisher_id%
        adsense_slots: %adsense_slots%
        adsense_slot_spec: %adsense_slot_spec%
        facebook_account: %facebook_account%
        facebook_client_id: %facebook_client_id%
        facebook_client_secret: %facebook_client_secret%
        facebook_app_version: %facebook_app_version%
        twitter_account: %twitter_account%

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            enumtransaction: Viteloge\CoreBundle\Component\DBAL\EnumTransactionType
            stringy_simple_array: Acreat\CoreBundle\Component\DBAL\StringifySimpleArrayType
        mapping_types:
            enum: string
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        dql:
            numeric_functions:
                round: Acreat\CoreBundle\Component\ORM\Query\Functions\Round
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
