fos_js_routing:
    routes_to_expose: [ acreat_insee_area_show, viteloge_frontend_ad_carousel ]
    cache_control:
        public: true
        maxage: 3600
        smaxage: 3600
        expires: "1 hour"
        vary: []
