fos_elastica:
    clients:
        default: { host: %elastic_host%, port: %elastic_port% }
    #serializer:
    #    callback_class: FOS\ElasticaBundle\Serializer\Callback
    #    serializer: serializer
    indexes:
        viteloge:
            index_name: viteloge_%kernel.environment%
            client: default
            settings:
                index:
                    analysis:
                        analyzer:
                            custom_lowercase_analyser:
                                type: custom
                                tokenizer: standard
                                filter: ["standard", "lowercase"]
                            custom_search_analyzer:
                                type: custom
                                tokenizer: standard
                                filter: ["asciifolding", "standard", "lowercase"] #"french_stem"
                            custom_index_analyzer:
                                type: custom
                                tokenizer: standard
                                filter: ["asciifolding", "standard", "lowercase", "custom_filter"]
                        filter:
                            custom_filter:
                                type: edgeNGram
                                side: front
                                min_gram: 1
                                max_gram: 10
            types:
                inseeArea:
                    mappings:
                        id:
                            type: string
                        keywords:
                            type: string
                    _parent:
                        type: "inseeCity"
                        property: "inseeCity"
                        identifier: "id"
                    persistence:
                        driver: orm
                        model: Acreat\InseeBundle\Entity\InseeArea
                        provider:
                            batch_size: 100
                        listener:
                            immediate: ~
                        finder: ~
                        elastica_to_model_transformer:
                            ignore_missing: true
                inseeCity:
                    mappings:
                        uname: ~
                        name:
                            type: "string"
                            boost: 5
                            search_analyzer: custom_search_analyzer
                            index_analyzer: custom_index_analyzer
                        fullname:
                            boost: 5
                        postalCode:
                            type: "string"
                            boost: 4
                            index_analyzer: custom_index_analyzer
                        id:
                            type: "string"
                        location:
                            type : "geo_point"
                        isCapital:
                            type: "integer"
                        population:
                            type: "integer"
                        inseeState:
                            type: "nested"
                            properties:
                                state_uname:
                                    property_path: uname
                                state_name:
                                    property_path: name
                                state_id:
                                    property_path: id
                                    type: "string"
                        inseeDepartment:
                            type: "nested"
                            properties:
                                department_uname:
                                    property_path: uname
                                department_name:
                                    property_path: name
                                id:
                                    property_path: id
                                    type: "string"
                    persistence:
                        driver: orm
                        model: Acreat\InseeBundle\Entity\InseeCity
                        provider:
                            batch_size: 100
                        listener:
                            immediate: ~
                        finder: ~
                        elastica_to_model_transformer:
                            ignore_missing: true
                ad:
                    mappings:
                        transaction:
                            type: "string"
                            boost: 5
                            search_analyzer: custom_lowercase_analyser
                        type:
                            type: "string"
                            boost: 4
                            index: "not_analyzed"
                        cityName:
                            type: "string"
                            boost: 3
                            analyzer: custom_search_analyzer
                        postalCode:
                            type: "string"
                            boost: 2
                        price:
                            type: "float"
                            boost: 2
                        createdAt :
                            type : "date"
                            boost: 1
                        rooms:
                            type: "integer"
                            boost: 2
                        surface:
                            type: "integer"
                            boost: 2
                        description:
                            type: "string"
                            boost: 1
                            search_analyzer: custom_search_analyzer
                        descriptionMku:
                            type: "string"
                            boost: 1
                            search_analyzer: custom_search_analyzer
                        privilegeRank:
                            type: "integer"
                            boost: 9
                        order:
                            type: "float"
                            boost: 8
                    _parent:
                        type: "inseeCity"
                        property: "inseeCity"
                        identifier: "id"
                    persistence:
                        driver: orm
                        model: Viteloge\CoreBundle\Entity\Ad
                        provider:
                            batch_size: 100
                        listener:
                            immediate: ~
                        finder: ~
                        elastica_to_model_transformer:
                            ignore_missing: true
