viteloge_glossary:
    resource: "@VitelogeGlossaryBundle/Resources/config/routing.yml"
    prefix:   /

viteloge_frontend:
    resource: "@VitelogeFrontendBundle/Resources/config/routing.yml"
    prefix:   /

acreat_insee:
    resource: "@AcreatInseeBundle/Resources/config/routing.yml"
    prefix:   /

acreat_core:
    resource: "@AcreatCoreBundle/Resources/config/routing.yml"
    prefix:   /

viteloge_core:
    resource: "@VitelogeCoreBundle/Resources/config/routing.yml"
    prefix:   /
