security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    acl:
        connection: default

    role_hierarchy:
        ROLE_OPERATOR: ROLE_USER
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                check_path: fos_user_security_check
                login_path: fos_user_security_login
                use_forward: false
                always_use_default_target_path: false
                default_target_path: viteloge_frontend_user_index
                use_referer: true
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager
                #intention: form_item
            logout:
                invalidate_session: true
                delete_cookies: ~
                path: fos_user_security_logout
            remember_me:
                key: %secret%
                lifetime: 604800
                path: /
                always_remember_me: true
                domain: %domain%
                secure: false
            anonymous: true
            oauth:
                resource_owners:
                    facebook: "/user/login/check-facebook"
                    twitter: "/user/login/check-twitter"
                    google: "/user/login/check-google"
                    github: "/user/login/check-github"
                login_path: fos_user_security_login
                use_forward: false
                failure_path: fos_user_security_login
                oauth_user_provider:
                    service: hwi_oauth.user.provider.fosub_bridge

    access_control:
         #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/user, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin/, role: ROLE_ADMIN }

        # DO NOT COMMIT BEYOND
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # ...
