security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    acl:
        connection: default

    role_hierarchy:
        ROLE_OPERATOR: ROLE_USER
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            stateless: true
            form_login:
                check_path: fos_user_security_check
                login_path: fos_user_security_login
                use_forward: false
                always_use_default_target_path: false
                default_target_path: viteloge_frontend_user_index
                use_referer: true
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:
                path: fos_user_security_logout
            remember_me:
                key: %secret%
                lifetime: 604800
                path: /
                domain: %domain%
                secure: false
            anonymous: true

    access_control:
         #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/user, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin/, role: ROLE_ADMIN }

        # DO NOT COMMIT BEYOND
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # ...
