sonata_seo:
    #default: sonata.seo.page.default
    encoding: UTF-8
    page:
        title: Fast Housing
        metas:
            charset:
                utf-8: ''
            name:
                viewport: "width=device-width, initial-scale=1.0"
                MobileOptimized: "320"
                HandheldFriendly: "True"
                apple-itunes-app: "app-id=391727896"
                apple-mobile-web-app-capable: "yes"
                apple-mobile-web-app-status-bar-style: "default"
                keywords: "immobilier, immo, viteloge, vente, achat, location, particulier, annonce, petite-annonce, logement, appart, appartement, studio, maison, pavillon, villa, demenagement, agence, notaire, loft, duplex, paris, marseille, lille, bordeaux,lyon, nantes, toulouse, rennes"
                description: "Immobilier - Vitelogé, Le moteur de recherche de l'immobilier. Acheter une maison, louer un appartement? Vitelogé est le site immobilier d'annonces immobilières de ventes et locations de logement en France. Plus de 900 000 annonces de professionnels pour les particuliers."
                robots: "index, follow"
                google: "notranslate"
                include_mode: "async"
                msapplication-TileColor: "#fff"
                msapplication-TileImage: "/mstile-144x144.png"
                theme-color: "#fff"
            property:
                # Facebook application settings
                'fb:app_id': "588522051250560"
                # Régis Hautière, Donald Inou, Adrien Loyant
                'fb:admins': "588583794,592056736,100002592573784"
                # ViteLoge (fr)
                'fb:page_id': "67401135398"

                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                'og:site_name': "Vitelogé : Le moteur de recherche de l'immobilier"
                'og:locale': "fr_FR"
                'og:title': "Immobilier - Vitelogé - Le moteur de recherche de l'immobilier"
                'og:image': "http://media.viteloge.com/bundles/vitelogecore/images/logo-viteloge-small.png"
                'og:description': "Immobilier - Vitelogé, Le moteur de recherche de l'immobilier. Acheter une maison, louer un appartement? Vitelogé est le site immobilier d'annonces immobilières de ventes et locations de logement en France. Plus de 900 000 annonces de professionnels pour les particuliers."
            http-equiv:
                'Content-Type': "text/html; charset=utf-8"
                'X-Ua-Compatible': "IE=edge"
        head:
            "lang": %locale%
            "xmlns": "http://www.w3.org/1999/xhtml"
            "xmlns:og": "http://opengraphprotocol.org/schema/"
            "xmlns:fb": "http://www.facebook.com/2008/fbml"
            "xmlns:hx": "http://purl.org/NET/hinclude"
