sonata_seo:
    #default: sonata.seo.page.default
    encoding: UTF-8
    page:
        title: Fast Housing
        metas:
            charset:
                utf-8: ''
            name:
                viewport: "width=device-width, initial-scale=1.0"
                MobileOptimized: "320"
                HandheldFriendly: "True"
                apple-itunes-app: "app-id=391727896"
                apple-mobile-web-app-capable: "yes"
                apple-mobile-web-app-status-bar-style: "default"
                keywords: "immobilier, immo, viteloge, vente, achat, location, particulier, annonce, petite-annonce, logement, appart, appartement, studio, maison, pavillon, villa, demenagement, agence, notaire, loft, duplex, paris, marseille, lille, bordeaux,lyon, nantes, toulouse, rennes"
                description: "Immobilier - ViteLogé, le moteur de recherche immobilier le plus rapide. Acheter une maison, louer un appartement : site immobilier d'annonces immobilières de ventes et locations de logement en France. Plus de 900 000 annonces de professionnels pour les particuliers"
                robots: "index, follow"
                include_mode: "async"
                msapplication-TileColor: '#000'
            property:
                # Facebook application settings
                #'fb:app_id':          XXXXXX
                'fb:admins': "588583794,724810804"

                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                'og:site_name': "Fast Housing"
                'og:title': "ViteLogé : le moteur de recherche immobilier le plus rapide !"
                'og:image': "http://www.viteloge.com/img/viteloge_logo.png"
                'og:description': "Site immobilier d'annonces immobilières de ventes et locations de logement en France."
            http-equiv:
                'Content-Type': "text/html; charset=utf-8"
                'X-Ua-Compatible': "IE=edge"
        head:
            "lang": %locale%
            "xmlns": "http://www.w3.org/1999/xhtml"
            "xmlns:og": "http://opengraphprotocol.org/schema/"
            "xmlns:fb": "http://www.facebook.com/2008/fbml"
            "xmlns:hx": "http://purl.org/NET/hinclude"
