sonata_seo:
    #default: sonata.seo.page.default
    encoding: UTF-8
    page:
        title: Fast Housing
        metas:
            name:
                viewport: "width=device-width, initial-scale=1.0"
                MobileOptimized: "320"
                HandheldFriendly: "True"
                apple-mobile-web-app-capable: "yes"
                apple-mobile-web-app-status-bar-style: "default"
                keywords: "foo bar"
                description: "The description"
                robots: "index, follow"
            property:
                # Facebook application settings
                #'fb:app_id':          XXXXXX
                #'fb:admins':          admin1, admin2

                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                'og:site_name': Fast Housing
                'og:description': Fast housing description
            http-equiv:
                'Content-Type': text/html; charset=utf-8
                #'X-Ua-Compatible': IE=EmulateIE7
            charset:
                utf-8: ''
        head:
            "lang": %locale%
            "xmlns": "http://www.w3.org/1999/xhtml"
            "xmlns:og": "http://opengraphprotocol.org/schema/"
            "xmlns:fb": "http://www.facebook.com/2008/fbml"
