parameters:
    acreat_core.form.type.tel.class: Acreat\CoreBundle\Form\Type\TelType
services:
    acreat.form.type.tel:
        class: %acreat_core.form.type.tel.class%
        tags:
            - { name: form.type, alias: tel }
