<?php

namespace Viteloge\CoreBundle\Repository {

    use Acreat\CoreBundle\Component\ORM\EntityRepository;

    /**
     * AdRepository
     *
     * This class was generated by the Doctrine ORM. Add your own custom
     * repository methods below.
     */
    class AdRepository extends EntityRepository {

        public function countByFiltered(array $criteria=null, array $orderBy = null) {
            $first = true;
            $query = $this->createQueryBuilder('a')
                ->select('count(a.id)');
            if (!empty($criteria) && is_array($criteria)) {
                foreach ($criteria as $key => $value) {
                    if (!$this->getClassMetadata()->hasField($key) && !$this->getClassMetadata()->hasAssociation($key)) {
                        continue;
                    }
                    $expr = $query->expr()->eq('a.'.$key, ':'.$key);
                    if ($first) {
                        $query->where($expr);
                        $first = false;
                    } else {
                        $query->andWhere($expr);
                    }
                    $query->setParameter($key, $value);
                }
            }
            if (!empty($orderBy) && is_array($orderBy)) {
                foreach ($orderBy as $key => $value) {
                    $query->orderBy('a.'.$key, $value);
                }
            }
            return $query->getQuery()->getSingleScalarResult();
        }

        /**
         * Finds entities by the agencyId "new".
         *
         * @param array|null $orderBy
         * @param int|null   $limit
         * @param int|null   $offset
         *
         * @return array The objects.
         */
        public function findByAgencyIdNew(array $orderBy = null, $limit = null, $offset = null) {
            $criteria['agencyId'] = constant($this->_entityName.'::AGENCY_ID_NEW');
            return $this->findBy($criteria, $orderBy, $limit, $offset);
        }

    }


}
