<?php

namespace Viteloge\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * AgenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgenceRepository extends EntityRepository
{
    public function getVisits( $agence )
    {
        $rsm = new ResultSetMapping();
        $rsm->addScalarResult( 'nbVisits', 'nbVisits' );

        $query = $this->_em->createNativeQuery(
            "SELECT COUNT(*) as nbVisits FROM statistiques WHERE idAgence IN ( SELECT idAgence FROM agence WHERE idAgenceMere = :idAgence OR idAgence = :idAgence ) AND EXTRACT( YEAR_MONTH FROM date ) = EXTRACT( YEAR_MONTH FROM NOW() - INTERVAL 1 MONTH )", $rsm
                                                   )
                ->setParameter( 'idAgence', $agence->id );
        $x = $query->getScalarResult();
        return $x[0]['nbVisits'];
    }

}
