<?php

namespace Viteloge\CoreBundle\Repository {

    use Acreat\CoreBundle\Component\ORM\EntityRepository;
    use Acreat\InseeBundle\Entity\InseeCity;

    /**
     * DistanceRepository
     *
     * This class was generated by the Doctrine ORM. Add your own custom
     * repository methods below.
     */
    class DistanceRepository extends EntityRepository {

        /**
         * legacy: inherits from VitelogeEstimation
         */
        public function findNeighbors( InseeCity $city, $distance, $nb_matches ) {
            $qb = $this->_em->createQueryBuilder();
            $qb
                ->select( 'distance' )
                ->addSelect( 'city' )
                ->from( 'VitelogeCoreBundle:Distance', 'distance' )
                ->leftJoin( 'distance.inseeTo', 'city' )
                ->andWhere( 'distance.inseeFrom = :city' )
                ->andWhere( 'distance.googleDistance < :distance')
                ->addOrderBy( 'distance.googleDistance', 'ASC' )
                ->setParameter( 'city', $city )
                ->setParameter( 'distance', $distance )
                ->setMaxResults( $nb_matches )
            ;
            return $qb->getQuery()->getResult();
        }

    }


}
