<?php

namespace Viteloge\CoreBundle\Repository {

    use Doctrine\ORM\EntityRepository;

    /**
     * DistanceRepository
     *
     * This class was generated by the Doctrine ORM. Add your own custom
     * repository methods below.
     */
    class DistanceRepository extends EntityRepository
    {
    }


}
