<?php

namespace Viteloge\CoreBundle\Repository;

use Acreat\CoreBundle\Component\ORM\EntityRepository;

/**
 * InseeVitelogeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InseeVitelogeRepository extends EntityRepository
{
}
