<?php

namespace Viteloge\CoreBundle\Repository {

    use Doctrine\ORM\EntityRepository;

    /**
     * InseeVitelogeStatsRepository
     *
     * This class was generated by the Doctrine ORM. Add your own custom
     * repository methods below.
     */
    class InseeVitelogeStatsRepository extends EntityRepository
    {
    }

}
