<?php

namespace Viteloge\CoreBundle\Repository {

    use Acreat\CoreBundle\Component\ORM\EntityRepository;

    /**
     * QueryStatsRepository
     *
     * This class was generated by the Doctrine ORM. Add your own custom
     * repository methods below.
     */
    class QueryStatsRepository extends EntityRepository {

        /**
         *
         */
        public function findOneByUrlrewrite($urlrewrite) {
            return $this->findOneBy(array('urlrewrite' => $urlrewrite));
        }

    }

}
