<?php

namespace Acreat\InseeBundle\Repository {

    use Doctrine\ORM\EntityRepository;
    use Doctrine\ORM\NoResultException;

    /**
     * InseeCityRepository
     *
     * This class was generated by the Doctrine ORM. Add your own custom
     * repository methods below.
     */
    class InseeCityRepository extends EntityRepository {

        public function findOneByLatLng($lat, $lng, $precision=2) {
            $query = $this->getEntityManager()
                ->createQuery(
                    'SELECT ic '.
                    'FROM AcreatInseeBundle:InseeCity ic '.
                    'WHERE ROUND(ic.lat, :precision) = :lat '.
                    'AND ROUND(ic.lng, :precision) = :lng '
                )
                ->setParameter('lat', $lat)
                ->setParameter('lng', $lng)
                ->setParameter('precision', $precision)
                ->setMaxResults(1);
             try {
                return $query->getSingleResult();
            } catch (NoResultException $e) {
                return null;
            }
        }

    }

}
