<?php

namespace Acreat\InseeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InseeCityhallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InseeCityhallRepository extends EntityRepository
{
}
