<?php

namespace Acreat\InseeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InseeDepartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InseeDepartmentRepository extends EntityRepository
{
}
