<?php

namespace Acreat\InseeBundle\Repository {

    use Doctrine\ORM\EntityRepository;
    use Doctrine\ORM\NoResultException;

    /**
     * InseeDepartmentRepository
     *
     * This class was generated by the Doctrine ORM. Add your own custom
     * repository methods below.
     */
    class InseeDepartmentRepository extends EntityRepository {

        /**
         *
         */
        public function findOneBySoundex($soundex) {
            $query = $this->getEntityManager()
                ->createQuery(
                    'SELECT i '.
                    'FROM AcreatInseeBundle:InseeDepartment i '.
                    'WHERE SOUNDEX(i.name) = SOUNDEX(:soundex) '
                )
                ->setParameter(':soundex', $soundex)
                ->setMaxResults(1);
            try {
                return $query->getSingleResult();
            } catch (NoResultException $e) {
                return null;
            }
        }

    }

}
