parameters:
    twig.extension.intl.class: Twig_Extensions_Extension_Intl
    twig.extension.date.class: Twig_Extensions_Extension_Date

services:
    twig.extension.intl:
        class: %twig.extension.intl.class%
        tags:
            - { name: twig.extension }
    twig.extension.date:
        class: %twig.extension.date.class%
        arguments: [@translator]
        tags:
            - { name: twig.extension }
