services:
#    viteloge_core.example:
#        class: Viteloge\CoreBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    twig.extension.date:
        class: Twig_Extensions_Extension_Date
        arguments: [@translator]
        tags:
            - { name: twig.extension }
